export { default as PlayerDetailModal } from "./PlayerDetailModal";
export type { PlayerDetail } from "./PlayerDetailModal";
export { default as CreatePlayerModal } from "./CreatePlayerModal";
export { default as EditPlayerModal } from "./EditPlayerModal";
export { default as StaffManagementModal } from "./StaffManagementModal";
export type { TeamStaff } from "./StaffManagementModal";
export { default as TeamMatchHistory } from "./TeamMatchHistory";
export type { TeamMatch } from "./TeamMatchHistory";
export { default as TransferPlayerModal } from "./TransferPlayerModal";
export { default as FirePlayerModal } from "./FirePlayerModal";
